development:
  adapter: postgresql
  database: bloghl_development
  host: localhost
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: bloghl_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bloghl_production
  host: 
  pool: 5
  timeout: 5000