development:
  adapter: postgresql
  database: bloghl_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: bloghl_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bloghl_production
  pool: 5
  timeout: 5000